stages:
  # test already exist by default
  # deploy too
  - test
  - benchmark
  # - deploy

# common stuff and actions
# how to specify multiple python versions? matrix?
image: conda/miniconda3
# python:3.13

default:
  tags:
    - ci.inria.fr # For using shared runners
    - small # For selecting small shared runners

before_script:
  - conda create -n ci-env python=3.10
  - conda activate ci-env
  - pip install -r requirements.txt
  - conda install libmambapy # in case not resolved by pip

test:
  stage: test
  # remove. will run as soon as there is an event on the BRANCH
  # ci pipelines are branch based
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - pytest

benchmark:
  stage: benchmark
  script:
    - asv run ALL
    - asv publish
  artifacts:
    paths:
      - .asv/html

pages:
  stage: benchmark
  script:
    - mv .asv/html public
  artifacts:
    paths:
      - public
  only:
    - main

# activate gitlab pages
# public is created in the pages job above.
# DOESN't WORK
# create-pages:
#   pages:
#     # The folder that contains the files to be exposed at the Page URL
#     publish: public
#   rules:
#     # This ensures that only pushes to the default branch will trigger
#     # a pages deploy
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

