# gitlab: repo toujours en checkout
# each job is in a fresh vm!
include:
  - project: "inria-ci/docker"
    file: "/register-dockerfile/register-dockerfile.yml"

stages:
  # test already exist by default
  # deploy too
  - test
  # - benchmark
  # - deploy

prepare:
  before_script: []
  rules:
    - changes:
        - Dockerfile
        - environment.yml
        - requirements.txt
  extends: .register-dockerfile-prepare

image: $image

# common stuff and actions
# how to specify multiple python versions? matrix?
default:
  before_script:
    - . ~/.bashrc
    - conda activate stellar-numerics
  tags:
    - ci.inria.fr # For using shared runners
    - large # For selecting large shared runners. Needed for big tests

test:
  stage: test
  # remove. will run as soon as there is an event on the BRANCH
  # ci pipelines are branch based
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "push"
  script:
  # all tests in their own threads if --isolate
    - pytest #--isolate

# benchmark:
#   stage: benchmark
#   script:
#     - asv run --show-stderr
#     # GitLab CI only fetches a shallow clone by default
#     - git fetch origin main
#     # Creates a local main branch that tracks the remote origin/main
#     - git checkout -b main origin/main
#     - asv publish
#   artifacts:
#     paths:
#       - html

# pages:
#   stage: deploy
#   dependencies:
#     - benchmark
#   script:
#     - mv html public
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
# activate gitlab pages
# public is created in the pages job above.
# DOESN't WORK
# create-pages:
#   pages:
#     # The folder that contains the files to be exposed at the Page URL
#     publish: public
#   rules:
#     # This ensures that only pushes to the default branch will trigger
#     # a pages deploy
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH



# The difference between needs and dependencies in GitLab CI lies in their purpose and behavior within a pipeline. needs is used to define the execution dependencies between jobs, allowing jobs to start as soon as their dependencies are met, regardless of the stage.
#  This enables more efficient pipeline execution by not waiting for entire stages to complete before starting subsequent jobs.
#  On the other hand, dependencies is used to specify which artifacts should be downloaded from previous jobs, focusing on the artifacts rather than the execution order.
#  While needs dictates the order in which jobs are executed, dependencies controls which artifacts are available to a job.
#  It is important to note that all jobs specified in dependencies must also be present in needs, otherwise the pipeline will not start.
