site_name: stellar-numerics
site_description: Documentation for stellar-numerics

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: false
            docstring_style: numpy
            members_order: source
            show_root_heading: true
            show_root_full_path: false

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md
